services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: 5432

  - type: web  # Ou "worker" si tu veux que Flet tourne sans page publique
    name: flet-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Flet_App/main.py
