# Generated by Django 5.1.3 on 2025-06-17 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('type_operation', models.CharField(choices=[('DEPENSE', 'Dépense'), ('RECETTE', 'Recette')], max_length=20, verbose_name="Type d'opération")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT_FINANCE', 'Agent Financier'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Rôle de l'agent")),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service ou département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant de l'opération")),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('description', models.TextField(blank=True, verbose_name="Description de l'opération")),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.agent', verbose_name='Agent associé')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['date', 'categorie__nom'],
            },
        ),
    ]
