# Generated by Django 5.1.3 on 2025-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_agent_options_remove_agent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent '), ('AUTRE', 'Autre')], max_length=20, verbose_name="Rôle de l'agent"),
        ),
    ]
