# Generated by Django 5.1.3 on 2025-06-19 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_agent_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['role', 'username'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='username',
        ),
    ]
