# Generated by Django 5.1.3 on 2025-06-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_agent_options_rename_user_agent_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['role', 'user'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='username',
            new_name='user',
        ),
    ]
