# Generated by Django 5.2.3 on 2025-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_agent_options_rename_username_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Rôle de l'agent"),
        ),
    ]
