# Generated by Django 5.2.3 on 2025-07-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget global', 'verbose_name_plural': 'Budgets globaux'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='mois',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='montant_max',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='utilisateur',
        ),
    ]
