# Generated by Django 5.2.3 on 2025-07-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_budget_options_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
