# Generated by Django 5.2.3 on 2025-07-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_delete_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Mois concerné (ex: 2025-07-01 pour juillet 2025)')),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Budget total pour le mois', max_digits=12)),
            ],
            options={
                'verbose_name': 'Budget Mensuel Global',
                'verbose_name_plural': 'Budgets Mensuels',
                'unique_together': {('mois',)},
            },
        ),
        migrations.CreateModel(
            name='SuiviCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant_depense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='management.categorie')),
            ],
            options={
                'verbose_name': 'Suivi par Catégorie',
                'verbose_name_plural': 'Suivis de Catégories',
                'unique_together': {('mois', 'categorie')},
            },
        ),
    ]
