# Generated by Django 5.2.3 on 2025-07-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_budgetmensuel_suivicategorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetmensuel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='budgetmensuel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetmensuel',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetmensuel',
            name='mois',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budgetmensuel',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='budgetmensuel',
            unique_together={('utilisateur', 'mois')},
        ),
        migrations.CreateModel(
            name='BudgetCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_depense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='management.budgetmensuel')),
            ],
        ),
        migrations.DeleteModel(
            name='SuiviCategorie',
        ),
    ]
