# Generated by Django 5.2.3 on 2025-07-05 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_budgetmensuel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetmensuel',
            options={'verbose_name': 'Budget Mensuel', 'verbose_name_plural': 'Budgets Mensuels'},
        ),
        migrations.AlterField(
            model_name='budgetmensuel',
            name='mois',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='budgetmensuel',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BudgetCategorie',
        ),
    ]
