# Generated by Django 5.2.3 on 2025-07-09 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_budgetmensuel_options_alter_budgetmensuel_mois_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='budgetmensuel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('DEPENSE', 'Dépense'), ('ENTREE', 'Entrée de fonds')], max_length=10),
        ),
    ]
